# Google Cloud Build 設定檔案
# 用於建置 .NET 應用程式並部署到 Cloud Run

steps:
  # 第一步：建置 Docker 映像
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "-t"
      - "gcr.io/$PROJECT_ID/translatebot:$COMMIT_SHA"
      - "-t"
      - "gcr.io/$PROJECT_ID/translatebot:latest"
      - "."
    id: "build-image"

  # 第二步：推送映像到 Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/translatebot:$COMMIT_SHA"
    id: "push-image"
    waitFor: ["build-image"]

  # 第三步：推送 latest 標籤
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "gcr.io/$PROJECT_ID/translatebot:latest"
    id: "push-latest"
    waitFor: ["build-image"]

  # 第四步：部署到 Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: "gcloud"
    args:
      - "run"
      - "deploy"
      - "translatebot" # Cloud Run 服務名稱
      - "--image"
      - "gcr.io/$PROJECT_ID/translatebot:$COMMIT_SHA"
      - "--region"
      - "asia-east1" # 亞洲東部區域（台灣附近）
      - "--platform"
      - "managed"
      - "--allow-unauthenticated" # 允許未驗證的請求
      - "--port"
      - "8080"
      - "--memory"
      - "512Mi" # 記憶體限制
      - "--cpu"
      - "1" # CPU 限制
      - "--max-instances"
      - "10" # 最大實例數
      - "--min-instances"
      - "0" # 最小實例數（省錢）
      - "--concurrency"
      - "80" # 每個實例的並發請求數
      - "--timeout"
      - "300" # 請求超時時間（秒）
      - "--set-env-vars"
      - "ASPNETCORE_ENVIRONMENT=Production,ASPNETCORE_URLS=http://+:8080,GEMINI_MODEL_ID=gemini-2.5-flash-lite-preview-06-17,GEMINI_EMBEDDING_MODEL_ID=gemini-embedding-001,DATABASE_CONNECTION_STRING=Host=postgres;Port=5432;Database=translatebot;Username=postgres;Password=1"
      - "--set-secrets"
      - "GEMINI_API_KEY=GEMINI_API_KEY:latest,DATABASE_CONNECTION_STRING=DATABASE_CONNECTION_STRING:latest"
    id: "deploy-cloudrun"
    waitFor: ["push-image"]

# 建置超時時間
timeout: "1200s" # 20 分鐘

# 建置記錄設定
options:
  logging: CLOUD_LOGGING_ONLY

# 替換變數（可選）
substitutions:
  _SERVICE_NAME: "translatebot"
  _REGION: "asia-east1"
  _MEMORY: "1Gi"
  _CPU: "1"
  _MAX_INSTANCES: "10"
  _MIN_INSTANCES: "0"
